</head>
<body>
    <div class="card">
        <h1>🚀 黄祈亮的 CI/CD 实验项目 </h1>
        <p class="version">学号：2440335109 | Python {{ python_version }}</p>
        <div class="status">✅ 实验-部署成功</div>
        <div class="info">
            <p><span>容器 ID：</span>{{ hostname }}</p>
            <p><span>部署时间：</span>{{ deploy_time }}</p>
            <p><span>环境：</span>{{ environment }}</p>
        </div>
    </div>
</body>
</html>"""
